[build]
  command = "node generate-vdp.js"
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/blog/:slug"
  to = "/blog-post.html?slug=:slug"
  status = 200
  force = true

[[redirects]]
  from = "/admin"
  to = "/admin-dashboard.html"
  status = 200
  force = true

[[redirects]]
  from = "/admin/blog"
  to = "/admin-dashboard.html"
  status = 200
  force = true

[[redirects]]
  from = "/admin/upload"
  to = "/admin-dashboard.html"
  status = 200
  force = true
