#!/usr/bin/env node
// prerender-blog.js — Emit a static, crawlable HTML file per published blog post
// Reads blog-post.html as the template and writes blog/<slug>.html for every published post.
// Netlify serves /blog/<slug> from blog/<slug>.html; the unforced /blog/:slug rewrite in
// netlify.toml only fires when no static file exists (e.g. a post published since the last build).
// Comments and share buttons stay dynamic (assets/js/blog-post.js).
// Idempotent: previously generated files are removed before writing.

const fs = require('fs');
const path = require('path');
const { escapeHtml, escapeAttr } = require('./build-utils');
const { loadPublishedBlogPosts } = require('./blog-source');

// netlify.toml 301s the apex domain to www, so www is the host that actually serves.
const BLOG_ORIGIN = 'https://www.bellsforktruckandauto.com';
const SITE_NAME = 'Bells Fork Truck & Auto';
const DEFAULT_IMAGE = `${BLOG_ORIGIN}/assets/hero/shop-front-og.jpg`;
const ROBOTS = 'index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1';
const TEMPLATE_PATH = path.join(__dirname, 'blog-post.html');
const OUT_DIR = path.join(__dirname, 'blog');
const GENERATED_MARKER = '<!-- generated by prerender-blog.js — do not edit -->';

function postUrl(post) {
  return `${BLOG_ORIGIN}/blog/${post.slug}`;
}

function absoluteUrl(url) {
  const u = String(url || '').trim();
  if (!u) return '';
  try {
    return new URL(u, BLOG_ORIGIN).href;
  } catch {
    return '';
  }
}

const dateFormatter = new Intl.DateTimeFormat('en-US', {
  month: 'long',
  day: 'numeric',
  year: 'numeric',
  timeZone: 'America/New_York',
});

function isoDate(value) {
  const d = new Date(value || '');
  return Number.isNaN(d.getTime()) ? '' : d.toISOString();
}

function displayDate(value) {
  const d = new Date(value || '');
  return Number.isNaN(d.getTime()) ? '' : dateFormatter.format(d);
}

const ENTITIES = { amp: '&', lt: '<', gt: '>', quot: '"', '#39': "'", apos: "'", nbsp: ' ' };

/** Plain-text CMS field (title, category, tags): trim + collapse whitespace, nothing else. */
function cleanText(value) {
  return String(value || '')
    .replace(/\s+/g, ' ')
    .trim();
}

/** Text that may carry entities (excerpt is built from stripped HTML): decode common ones. */
function decodeText(value) {
  return cleanText(
    String(value || '').replace(/&(amp|lt|gt|quot|#39|apos|nbsp);/g, (_m, name) => ENTITIES[name])
  );
}

/** Article HTML -> plain text. */
function htmlToText(value) {
  return decodeText(String(value || '').replace(/<[^>]*>/g, ' '));
}

/** Everything a post's <head> and JSON-LD need, with CMS fallbacks applied. */
function postMeta(post) {
  const headline = cleanText(post.title);
  const description =
    decodeText(post.metaDescription) ||
    decodeText(post.excerpt) ||
    htmlToText(post.content).slice(0, 160);
  const published = isoDate(post.publishedAt || post.createdAt || post.updatedAt);
  return {
    url: postUrl(post),
    headline,
    title: `${headline} | ${SITE_NAME}`,
    description,
    image: absoluteUrl(post.featuredImage) || DEFAULT_IMAGE,
    published,
    modified: isoDate(post.updatedAt) || published,
    section: cleanText(post.category) || 'General',
    tags: (Array.isArray(post.tags) ? post.tags : []).map(cleanText).filter(Boolean),
  };
}

// ── Structured data ──

function buildBlogPostingSchema(post) {
  const m = postMeta(post);
  const org = { '@type': 'Organization', name: SITE_NAME, url: `${BLOG_ORIGIN}/` };
  const schema = {
    '@context': 'https://schema.org',
    '@type': 'BlogPosting',
    '@id': `${m.url}#article`,
    mainEntityOfPage: { '@type': 'WebPage', '@id': m.url },
    url: m.url,
    headline: m.headline,
    description: m.description,
    image: [m.image],
    datePublished: m.published || undefined,
    dateModified: m.modified || undefined,
    author: org,
    publisher: {
      ...org,
      logo: { '@type': 'ImageObject', url: `${BLOG_ORIGIN}/assets/logo.png` },
    },
    articleSection: m.section,
    keywords: m.tags.length ? m.tags.join(', ') : undefined,
    inLanguage: 'en-US',
  };
  return schema;
}

/** JSON for an inline <script>: escape "<" (and JS line separators) so content can't close the tag. */
function jsonForScript(value) {
  return JSON.stringify(value, null, 2)
    .replace(/</g, '\\u003c')
    .replace(/\u2028/g, '\\u2028')
    .replace(/\u2029/g, '\\u2029');
}

// ── Template surgery (throws if the template no longer has the expected anchors) ──

function mustReplace(html, pattern, replacer, label) {
  let matched = false;
  const out = html.replace(pattern, (...args) => {
    matched = true;
    return typeof replacer === 'function' ? replacer(...args) : replacer;
  });
  if (!matched) throw new Error(`blog-post.html template is missing expected anchor: ${label}`);
  return out;
}

/** Locate <tag ... id="id" ...>...</tag>, counting nested tags of the same name. */
function findElement(html, tag, id) {
  const openRe = new RegExp(`<${tag}\\b[^>]*\\bid="${id}"[^>]*>`);
  const m = openRe.exec(html);
  if (!m) throw new Error(`blog-post.html template is missing <${tag} id="${id}">`);
  const start = m.index;
  const innerStart = start + m[0].length;
  const tokenRe = new RegExp(`<${tag}\\b[^>]*>|</${tag}>`, 'g');
  tokenRe.lastIndex = innerStart;
  let depth = 1;
  let t;
  while ((t = tokenRe.exec(html))) {
    depth += t[0].startsWith('</') ? -1 : 1;
    if (depth === 0) {
      return { start, openTag: m[0], innerStart, innerEnd: t.index, end: t.index + t[0].length };
    }
  }
  throw new Error(`blog-post.html template has unbalanced <${tag} id="${id}">`);
}

function removeElement(html, tag, id) {
  const el = findElement(html, tag, id);
  return html.slice(0, el.start) + html.slice(el.end);
}

function setInner(html, tag, id, inner) {
  const el = findElement(html, tag, id);
  return html.slice(0, el.innerStart) + inner + html.slice(el.innerEnd);
}

function setOpenTag(html, tag, id, openTag) {
  const el = findElement(html, tag, id);
  return html.slice(0, el.start) + openTag + html.slice(el.innerStart);
}

// ── Page rendering ──

function renderHeadMeta(post) {
  const m = postMeta(post);
  const a = escapeAttr;
  const lines = [
    `<title id="pageTitle">${escapeHtml(m.title)}</title>`,
    `<meta name="description" id="metaDescription" content="${a(m.description)}" />`,
    `<meta name="robots" content="${ROBOTS}" />`,
    `<link rel="canonical" id="canonicalLink" href="${a(m.url)}" />`,
    `<meta property="og:type" content="article" />`,
    `<meta property="og:site_name" content="${a(SITE_NAME)}" />`,
    `<meta property="og:locale" content="en_US" />`,
    `<meta property="og:title" id="ogTitle" content="${a(m.title)}" />`,
    `<meta property="og:description" id="ogDescription" content="${a(m.description)}" />`,
    `<meta property="og:url" id="ogUrl" content="${a(m.url)}" />`,
    `<meta property="og:image" id="ogImage" content="${a(m.image)}" />`,
    `<meta property="og:image:alt" content="${a(m.headline)}" />`,
    m.published && `<meta property="article:published_time" content="${a(m.published)}" />`,
    m.modified && `<meta property="article:modified_time" content="${a(m.modified)}" />`,
    `<meta property="article:section" content="${a(m.section)}" />`,
    ...m.tags.map((t) => `<meta property="article:tag" content="${a(t)}" />`),
    `<meta name="twitter:card" content="summary_large_image" />`,
    `<meta name="twitter:title" id="twTitle" content="${a(m.title)}" />`,
    `<meta name="twitter:description" id="twDescription" content="${a(m.description)}" />`,
    `<meta name="twitter:image" id="twImage" content="${a(m.image)}" />`,
    `<meta name="twitter:image:alt" content="${a(m.headline)}" />`,
  ];
  return lines.filter(Boolean).join('\n  ');
}

function renderBody(html, post) {
  const url = postUrl(post);
  const title = String(post.title).trim();
  const shareText = `${title} | Bells Fork Truck & Auto`;

  // Loading / error placeholders are only meaningful for the client-rendered fallback
  html = removeElement(html, 'div', 'loadingState');
  html = removeElement(html, 'section', 'errorState');

  html = setOpenTag(
    html,
    'article',
    'article',
    `<article id="article" data-prerendered="true" data-slug="${escapeAttr(post.slug)}" data-title="${escapeAttr(title)}">`
  );
  html = setInner(html, 'span', 'postCategory', escapeHtml(post.category || 'General'));
  html = setInner(html, 'h1', 'postTitle', escapeHtml(title));

  const published = post.publishedAt || post.updatedAt;
  const dateText = displayDate(published);
  html = setInner(
    html,
    'span',
    'postDate',
    dateText
      ? `<time datetime="${escapeAttr(isoDate(published))}">${escapeHtml(dateText)}</time>`
      : ''
  );
  html = setInner(html, 'span', 'postAuthor', escapeHtml(post.author || 'Bells Fork Team'));

  const heroSrc = String(post.featuredImage || '').trim();
  if (heroSrc) {
    html = setOpenTag(html, 'div', 'postHero', '<div id="postHero" class="article-hero">');
    html = mustReplace(
      html,
      /<img id="postHeroImg"[^>]*>/,
      () =>
        `<img id="postHeroImg" src="${escapeAttr(heroSrc)}" alt="${escapeAttr(title)}" loading="eager" fetchpriority="high" />`,
      'img#postHeroImg'
    );
  } else {
    html = removeElement(html, 'div', 'postHero');
  }

  // No-JS share links (blog-post.js re-binds the same URLs and wires Copy Link)
  const enc = encodeURIComponent;
  html = mustReplace(
    html,
    /<a id="shareFacebook"([^>]*) href="#"/,
    (_m, attrs) =>
      `<a id="shareFacebook"${attrs} href="${escapeAttr(`https://www.facebook.com/sharer/sharer.php?u=${enc(url)}`)}"`,
    'a#shareFacebook'
  );
  html = mustReplace(
    html,
    /<a id="shareX"([^>]*) href="#"/,
    (_m, attrs) =>
      `<a id="shareX"${attrs} href="${escapeAttr(`https://x.com/intent/tweet?url=${enc(url)}&text=${enc(shareText)}`)}"`,
    'a#shareX'
  );
  html = mustReplace(
    html,
    /<a id="shareEmail"([^>]*) href="#"/,
    (_m, attrs) =>
      `<a id="shareEmail"${attrs} href="${escapeAttr(`mailto:?subject=${enc(shareText)}&body=${enc(url)}`)}"`,
    'a#shareEmail'
  );

  // Article body last: CMS HTML is admin-authored and rendered as-is (same as the client's innerHTML)
  html = setInner(html, 'section', 'postContent', `\n${post.content}\n`);
  return html;
}

function renderPostPage(template, post) {
  let html = template;

  // Title, description, robots, canonical, Open Graph, article:* and Twitter tags
  html = mustReplace(
    html,
    /<!-- blog:head-meta\b[^>]*-->[\s\S]*?<!-- \/blog:head-meta -->/,
    () => renderHeadMeta(post),
    'blog:head-meta markers'
  );
  // Replace the template's placeholder BlogPosting JSON-LD with this post's
  html = mustReplace(
    html,
    /<!-- BlogPosting JSON-LD[^>]*-->(\s*)<script type="application\/ld\+json" id="blogPostingSchema">[\s\S]*?<\/script>/,
    (_m, ws) =>
      `<!-- BlogPosting JSON-LD (prerender-blog.js) -->${ws}<script type="application/ld+json" id="blogPostingSchema">\n${jsonForScript(buildBlogPostingSchema(post))}\n  </script>`,
    'script#blogPostingSchema'
  );

  html = renderBody(html, post);
  return html.replace(/<!DOCTYPE html>/i, (m) => `${m}\n${GENERATED_MARKER}`);
}

// ── Output management ──

function cleanGeneratedFiles() {
  if (!fs.existsSync(OUT_DIR)) return 0;
  let removed = 0;
  for (const name of fs.readdirSync(OUT_DIR)) {
    if (!name.endsWith('.html')) continue;
    const file = path.join(OUT_DIR, name);
    if (fs.readFileSync(file, 'utf8').includes(GENERATED_MARKER)) {
      fs.unlinkSync(file);
      removed++;
    }
  }
  return removed;
}

async function main() {
  const posts = await loadPublishedBlogPosts();
  if (posts === null) {
    console.log('Blog prerender skipped (no blog source configured).');
    return;
  }

  const template = fs.readFileSync(TEMPLATE_PATH, 'utf8');
  // Render everything before touching disk so a template error can't leave a half-written blog/
  const pages = posts.map((post) => ({ post, html: renderPostPage(template, post) }));

  const removed = cleanGeneratedFiles();
  fs.mkdirSync(OUT_DIR, { recursive: true });
  for (const { post, html } of pages) {
    fs.writeFileSync(path.join(OUT_DIR, `${post.slug}.html`), html, 'utf8');
  }

  console.log(`Blog prerendered: ${pages.length} published post(s) -> blog/<slug>.html`);
  if (removed) console.log(`  - Removed ${removed} previously generated file(s)`);
}

if (require.main === module) {
  main().catch((err) => {
    console.error(`[prerender-blog] FAILED: ${err.stack || err.message}`);
    process.exit(1);
  });
}

module.exports = {
  renderPostPage,
  postMeta,
  buildBlogPostingSchema,
  postUrl,
  absoluteUrl,
  htmlToText,
  BLOG_ORIGIN,
  GENERATED_MARKER,
};
